### ISSUE TITLE
Moving down on escape

### ISSUE THREAD

**Issue by ldebritto** [Appccessibility-Shox/Keys#37]
When pressing `Esc` to escape the overlay, page moves to the Botton.

Using Safari 15.4 and macOS 12.3.

**Comment by patrickshox** [comment]
Yes, I've known about this bug for a while. I actually fixed it back in September, but never bothered submitting a new build to AppStoreConnect because it's a relatively minor bug. However, last night I submitted versions 1.1 (iPadOS) and 5 (macOS) of Keys, which will resolve this issue.
https://github.com/Appccessibility-Shox/Keys/blob/7afbb2cd099a3d0a8af04135ce1e4619151dfa13/Shared%20(Extension)/Resources/keys.js#L50
